### PR TITLE
 The plot.html breaks the plot.html widget! 

### PR DESCRIPTION
**Pull request by BlackBird77**
Please Merge!!

### CODE REVIEW

**Comment by Apollon77** [comment]
Do you know the status of smartvisu release? Plan was to wait for " a long awaited new version" and then officially introduce the adapter. Is this version out there? Should we not better sync the whole "dist" directory to the current status of the smartvisu project instead fixing one single thing?

**Comment by BlackBird77** [comment]
OK. I currently have no issues with the beta version of the development industry. I thought it would be better to fix the problem in the demo with the plots. I searched for 5 hours, why the plot did not work.

2019-03-08_16h57_02

2019-03-08_16h57_14

2019-03-08_16h57_40

2019-03-08_16h57_59

**Comment by Apollon77** [comment]
Then let’s fit he following. Please also create this PR in the real smartvisu repo and I accept here. I just want to make sure that once we do the full update it still works and the error do not come back then.

**Comment by BlackBird77** [comment]
ok no problem..

**Comment by BlackBird77** [comment]
Thank you.

The next weeks i create an handler to support the smartVisu Uzsu items in
the ioBroker Adapter.

If everything is tested i create another PR for the Uzsu Feature.



Ingo Fischer <notifications@github.com> schrieb am Fr., 8. März 2019, 22:56:

**Pull request merged**
